name: Demo

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Run number: ${{ github.run_number }}"
